# Include the QtPyVCP default menubar.
{% include "default_menubar.yml" %}

qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: Craftsman
  version: v0.0.1
  author: Jiri Prochazka
  description: >
    Put a short description of your VCP here. This will be
    shown in the VCP Chooser when launching QtPyVCP with the
    --chooser option.


    Examples of what to included here:
      * VCP Features
      * Type of machine the VCP is for
      * Development status
      * Acknowledgments

data_plugins:
  status:
    kwargs:
      cycle_time: 75
  tooltable:
    kwargs:
      # specify the columns that should be read and writen to the
      # tooltable file. To use all columns set to: TPXYZABCUVWDIJQR
      columns: PTDZR
      # specify text to be added before the tool table data
      file_header_template: |
        LinuxCNC Tool Table

windows:

  mainwindow:
    # Specify the class to use for the VCP's mainwindow
    #   Format: package.module:class
    provider: craftsman.mainwindow:MyMainWindow

    # Keyword arguments to pass when initializing the class.
    kwargs:
      # Specify the mainwindow menubar as the default.
      menu: ( default_menubar )
      # Specify the UI file to load the window layout from.
      ui_file: {{ file.dir }}/ui/mainwindow.ui
      # Specify a stylesheet to use only for mainwindow.
      stylesheet: null
      # Set the window title from from the date in the vcp section above.
      title: ( vcp.name ) ( vcp.version)

application:
  kwargs:
    # Specify the application wide stylesheet.
    stylesheet: {{ file.dir }}/ui/style.qss
dialogs:
  tooltable_dialog:
    provider: qtpyvcp.widgets.dialogs.base_dialog:BaseDialog
    kwargs:
      ui_file: {{ file.dir }}/ui/ToolTable.ui
      title: Tool table    # optional, set the dialog title
      #modal: false              # optional, whether the dialog is modal
      #popup: false              # optional, whether the dialog is a popup
      #frameless: true          # optional, whether the dialog is frameless
      stay_on_top: true         # optional, whether the dialog stays on top
