# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/prochj51/craftsman/craftsman/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 719)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color:rgb(46, 52, 54)")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("")
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalFrame = QtWidgets.QFrame(self.tab)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Upper = QtWidgets.QFrame(self.verticalFrame)
        self.Upper.setFrameShape(QtWidgets.QFrame.Box)
        self.Upper.setObjectName("Upper")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Upper)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalFrame1 = QtWidgets.QFrame(self.Upper)
        self.verticalFrame1.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gcodeeditor = GcodeEditor(self.verticalFrame1)
        self.gcodeeditor.setObjectName("gcodeeditor")
        self.verticalLayout_3.addWidget(self.gcodeeditor)
        self.mdientry = MDIEntry(self.verticalFrame1)
        self.mdientry.setObjectName("mdientry")
        self.verticalLayout_3.addWidget(self.mdientry)
        self.horizontalLayout_2.addWidget(self.verticalFrame1)
        self.verticalFrame2 = QtWidgets.QFrame(self.Upper)
        self.verticalFrame2.setStyleSheet("")
        self.verticalFrame2.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ProcessControl = QtWidgets.QFrame(self.verticalFrame2)
        self.ProcessControl.setFrameShape(QtWidgets.QFrame.Box)
        self.ProcessControl.setObjectName("ProcessControl")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ProcessControl)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridFrame = QtWidgets.QFrame(self.ProcessControl)
        self.gridFrame.setMaximumSize(QtCore.QSize(400, 800))
        self.gridFrame.setStyleSheet("QPushButton{\n"
"background-color:rgb(32, 74, 100);\n"
"border-radius:0px\n"
"}")
        self.gridFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_4.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridFrame)
        self.gridFrame_2 = QtWidgets.QFrame(self.ProcessControl)
        self.gridFrame_2.setStyleSheet("QPushButton{\n"
"min-height:50px;\n"
"max-width:100px;\n"
"border-radius:3px\n"
"}\n"
"\n"
"")
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.playButton_2 = QtWidgets.QPushButton(self.gridFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton_2.sizePolicy().hasHeightForWidth())
        self.playButton_2.setSizePolicy(sizePolicy)
        self.playButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(115, 210, 22);\n"
"border-radius:3px;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playButton_2.setIcon(icon)
        self.playButton_2.setIconSize(QtCore.QSize(24, 24))
        self.playButton_2.setCheckable(True)
        self.playButton_2.setObjectName("playButton_2")
        self.gridLayout_2.addWidget(self.playButton_2, 0, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridFrame_2)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"background-color:rgb(245, 121, 0);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 1, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridFrame_2)
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"background-color:rgb(204, 0, 0);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 2, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.gridFrame_2)
        self.verticalLayout_5.addWidget(self.ProcessControl)
        self.ChooseCOntrol = QtWidgets.QFrame(self.verticalFrame2)
        self.ChooseCOntrol.setStyleSheet("QPushButton{\n"
"background-color:rgb(32, 74, 100);\n"
"border-radius:0px;\n"
"border-line:2px;\n"
"min-height:30px\n"
"}")
        self.ChooseCOntrol.setFrameShape(QtWidgets.QFrame.Box)
        self.ChooseCOntrol.setObjectName("ChooseCOntrol")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ChooseCOntrol)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_13 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_3.addWidget(self.pushButton_10, 0, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_3.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 0, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_3.addWidget(self.pushButton_15, 1, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 2, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 2, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.ChooseCOntrol)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.ChooseCOntrol)
        self.horizontalLayout_2.addWidget(self.verticalFrame2)
        self.verticalFrame3 = QtWidgets.QFrame(self.Upper)
        self.verticalFrame3.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame3.setObjectName("verticalFrame3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vtkbackplot = VTKBackPlot(self.verticalFrame3)
        self.vtkbackplot.setObjectName("vtkbackplot")
        self.verticalLayout_4.addWidget(self.vtkbackplot)
        self.horizontalLayout_2.addWidget(self.verticalFrame3)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 5)
        self.horizontalLayout_2.setStretch(2, 4)
        self.verticalLayout_2.addWidget(self.Upper)
        self.Lower = QtWidgets.QFrame(self.verticalFrame)
        self.Lower.setFrameShape(QtWidgets.QFrame.Box)
        self.Lower.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Lower.setObjectName("Lower")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Lower)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.Lower)
        self.gridLayout.addWidget(self.verticalFrame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOPEN = QtWidgets.QAction(MainWindow)
        self.actionOPEN.setObjectName("actionOPEN")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFullscreen = QtWidgets.QAction(MainWindow)
        self.actionFullscreen.setCheckable(True)
        self.actionFullscreen.setObjectName("actionFullscreen")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.playButton_2.setText(_translate("MainWindow", "Play"))
        self.pushButton_19.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_20.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOPEN.setText(_translate("MainWindow", "oPEN"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionFullscreen.setText(_translate("MainWindow", "Fullscreen"))
        self.actionFullscreen.setShortcut(_translate("MainWindow", "F11"))

from qtpyvcp.widgets.display_widgets.vtk_backplot.vtk_backplot import VTKBackPlot
from qtpyvcp.widgets.input_widgets.gcode_editor import GcodeEditor
from qtpyvcp.widgets.input_widgets.mdientry_widget import MDIEntry
import resources_rc
